# config/application.yml
defaults: &defaults
  socket_url: 0.0.0.0:5001
  #socket_url: http://classroom.happycasts.net:5001
  awesome_setting: <%= "Did you know 5 + 5 = #{5 + 5}?" %>

development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
